[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "0x9d8b70"
blue = "0xb4a490"
cyan = "0xb49368"
green = "0x302b25"
magenta = "0xd7c8bc"
red = "0xca7f32"
white = "0xe4d4c8"
yellow = "0x48413a"

[colors.cursor]
cursor = "0xcabcb1"
text = "0x231e18"

[colors.normal]
black = "0x231e18"
blue = "0x88a4d3"
cyan = "0x6eb958"
green = "0xb7ba53"
magenta = "0xbb90e2"
red = "0xd35c5c"
white = "0xcabcb1"
yellow = "0xe0ac16"

[colors.primary]
background = "0x231e18"
foreground = "0xcabcb1"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Regular"

[window]
opacity = 0.8
